spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: triple
    password: triple
    url: jdbc:mysql://127.0.0.1:3306/triple
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true